language: go
go:
        - '1.0'
        - '1.3'
        - '1.6'
        - '1.8'
before_script:
        - 'go get golang.org/x/tools/cmd/cover'
        - 'go get github.com/mattn/goveralls'
script:
        - go env
        - go get -v ./...
        - go test -v -covermode=count -coverprofile=coverage.out 
        - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
        - go build
